### ISSUE TITLE
Comment color is to dim.

### ISSUE THREAD

**Issue by chigoncalves** [hlissner/emacs-doom-theme#11]
The current color used in `font-lock-comment-face` is so dim
that one can barelly read any comment in a source file, please
consider improving this.

**Comment by hlissner** [comment]
Sure, I'll look into it.

**Comment by hlissner** [comment]
With a recent commit I made doc-comments violet and _slightly_ brightened comment faces. Is that better?

I'd rather not go far beyond that (doom-one is supposed to be low-contrast, like Atom One's). I will have other colorschemes soon that are higher contrast, but in the meantime, you can modify those two comment faces in your configuration, like so:

```elisp
(custom-set-faces
 `(font-lock-comment-face           ((t (:inherit font-lock-builtin-face))))
 `(font-lock-comment-delimiter-face ((t (:inherit font-lock-builtin-face)))))
```

**Comment by hlissner** [comment]
Just introduced the `doom-enable-brighter-comments` option, as well as adjusted some of the bright-comment colors. Hopefully this helps!

**Comment by chigoncalves** [comment]
Perfect mate! A thousand thanks.

**Comment by EndlessDex** [comment]
Can a similar option be added for the molokai theme?
