### ISSUE TITLE
org-heading backgrounds

### ISSUE THREAD

**Issue by AnthonyDiGirolamo** [hlissner/emacs-doom-theme#13]
Thanks for the great colors! I really like the level 1 and 2 org mode headings. At first I couldn't figure out why I wasn't getting the background color across the whole line. Then I discovered the `org-fontify` variables. You might suggest setting these in the readme.

```emacs-lisp
(setq org-fontify-whole-heading-line t
      org-fontify-done-headline t
      org-fontify-quote-and-verse-blocks t)
```

edit: add org-fontify-quote-and-verse-blocks variable

**Comment by hlissner** [comment]
Ah, you're right! I took them for granted. I'll add them to the readme soon.

**Comment by hlissner** [comment]
And done. Thanks for letting me know!
