### ISSUE TITLE
Inactive modeline border

### ISSUE THREAD

**Issue by rakanalh** [hlissner/emacs-doom-theme#14]
Hello,

```
__________________
|        |        |
|________|        |
|        |        |
|        |        |
```

When having multiple buffers open in horizontal split, the modeline for the top buffer isn't very 
differentiable from the bottom buffer. Which is supposed to be the case given that the modeline should be the part which tells the top from the bottom buffer. However, the colors used for modeline when it's inactive makes it blend in the two open buffers making it a little hard to tell what you have in terms of layout.
So the question is:
Is it possible to add a visible border around inactive modeline for split buffers?

**Comment by hlissner** [comment]
Aye, I have a solution to this in the next commit.

However, if you run Emacs 25.1+, I recommend `window-divider-mode`::

```elisp
;; `window-divider-mode' gives us finer control over the border between windows.
;; The native border "consumes" a pixel of the fringe on righter-most splits (in
;; Yamamoto's emacs-mac at least), window-divider does not. You can also control 
;; vertical borders between windows (introduced in Emacs 25.1+)
(when (boundp 'window-divider-mode)
  (setq window-divider-default-places t
        window-divider-default-bottom-width 1
        window-divider-default-right-width 1)
  (window-divider-mode +1))
```

**Comment by rakanalh** [comment]
I've updated the repo and added the aforementioned snippet. The modeline is a little darker now making it easier to tell separate buffers.
Thanks
