### ISSUE TITLE
pos-tip support

### ISSUE THREAD

**Issue by mzgnr** [hlissner/emacs-doom-theme#15]
Thanks for your work 👍 

It would be nice to have pos-tip support
There is an example code

```
   `(pos-tip-foreground-color ,foreground)
   `(pos-tip-background-color , background)
```

**Comment by hlissner** [comment]
Sure, I'd be happy to add it. However, I'm having trouble finding the faces for pos-tip.el. Where did you get `pos-tip-foreground-color` and `pos-tip-background-color` from?

**Comment by mzgnr** [comment]
I found them in solarized-theme package, sadly they dont make any change. I've found this https://github.com/pitkali/pos-tip/pull/7

**Comment by hlissner** [comment]
Ah, it looks like pos-tip reads the background from the `tooltip` face, which is already customized. I'm guessing your tooltips still come up in the default black on beige? What OS are you running and what version of emacs?

**Comment by mzgnr** [comment]
@hlissner you are right. OS X 10.11.6

**Comment by hlissner** [comment]
I recall not finding any way around that in stock Emacs, and was one reason I switched to Matsumoto's [emacs-mac](https://github.com/railwaycat/homebrew-emacsmacport). If you have homebrew installed, you can install it with:

```elisp
brew tap railwaycat/emacsmacport
brew install emacs-mac --with-imagemagick --with-modern-icon --HEAD
```
