### ISSUE TITLE
Ediff colors are very stark

### ISSUE THREAD

**Issue by dakrone** [hlissner/emacs-doom-theme#16]
The `ediff-odd-diff-B` (A, B, and C) faces are using `light grey` as a background, which is very difficult to read.

Additionally, the highlighted changes (green ones) are a bit too bright to read when looking at a particular change.

Here's a screenshot showing what I'm talking about:

![screenshot from 2016-09-26 03-56-11](https://cloud.githubusercontent.com/assets/19060/18830320/72a404c2-839d-11e6-984c-9dd2f28074c2.png)

**Comment by hlissner** [comment]
You're right! I'll look into it.

**Comment by rakanalh** [comment]
@hlissner did you get the chance to look into this? i am finding my self doing diffs and conflict resolution more than ever and this is the only pain point i find in the theme.

**Comment by hlissner** [comment]
Yes. I've been experimenting. I've only recently switched from vimdiff, so I am still coming to grips with ediff. I should have something ready today.

**Comment by rakanalh** [comment]
Cool! Thanks for the quick reply... looking forward to this :)

**Comment by hlissner** [comment]
I've pushed (what I think) is a reasonable colorscheme for ediff, so I'll consider this resolved. I've only started regular use of ediff recently, so let me know if I've missed anything.
