### ISSUE TITLE
Gnus support

### ISSUE THREAD

**Issue by nlamirault** [hlissner/emacs-doom-theme#17]
Do you think it is possible to support Gnus faces ?

**Comment by hlissner** [comment]
Certainly, but I'm not familiar with them. Could you provide more information about them?

**Comment by nlamirault** [comment]
There is no difference between gnus-group-mail-3-empty and gnus-group-mail-3
It could be more user friendly to have different colors.

![2017-05-02-112023_272x92_scrot](https://cloud.githubusercontent.com/assets/29233/25612013/6c7ac45e-2f29-11e7-910e-1fb0c8fcdb41.png)

Also, gnus-summary-normal-unread is not very user friendly : 
![2017-05-02-112300_1107x30_scrot](https://cloud.githubusercontent.com/assets/29233/25612132/d49d01f0-2f29-11e7-811d-f63ffc886419.png)

**Comment by hlissner** [comment]
I'll look into this tomorrow. Unfortunately, I can't test my choices because I'm not a gnus user, so if you can suggest some colors/faces that would be of great help!

**Comment by nlamirault** [comment]
"green" for new mails and "green" for gnus-summary-normal-unread too ?

**Comment by hlissner** [comment]
Just pushed some changes (including your suggestion). Let me know if you see any problems.
