### ISSUE TITLE
enhance org-mode faces

### ISSUE THREAD

**Issue by stardiviner** [hlissner/emacs-doom-theme#18]
![screenshot_20161004_191408](https://cloud.githubusercontent.com/assets/378699/19072179/60f47fa2-8a66-11e6-9b77-c79bad0de44b.png)

This is the screenshot which `doom-one` theme has issue that some org-mode headlines are not colored.

And some org-mode faces like `org-priority` are not customized.
Hope you can add support to all org-mode faces from `customize-group org-faces`.

**Comment by hlissner** [comment]
You're correct, this is due to how I used org-mode at the time. I'll fix this soon.

**Comment by hlissner** [comment]
I've made headline colors more consistent and added `org-priority`. I'll investigate other org faces.

Are there any particular ones that stand out to you?

**Comment by rakanalh** [comment]
Seems like the issue is fixed. Thanks @hlissner
