### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by hlissner** [hlissner/emacs-doom-theme#19]
They are out of date.
- [x] Update neotree screenshots (with `(setq doom-neotree-file-icons 'simple)` and new variable-pitch labels)
- [x] Update full screenshot for `doom-one` (a lot has changed)

**Comment by SavchenkoValeriy** [comment]
Hello,
I've tried your theme and it's very different from the one on screenshots:
![merged](https://cloud.githubusercontent.com/assets/1611696/19483313/99a8a9da-955c-11e6-925c-242df14873ef.png)
It looks much brighter on your screenshots. Is it related to this issues?
Thanks!

**Comment by hlissner** [comment]
Assuming you are referring to the background color, this is because you aren't using `doom-buffer-mode` (the feature to brighten up source buffers). If you add `(add-hook 'find-file-hook 'doom-buffer-mode)` to your config, the background of code buffers (as opposed to shell, message or scratch buffers) will have a brighter background, like the screenshot.

Let me know if that helps. In the meantime, I'll need to look into making the brighter background the default when doom-buffer-mode isn't being used.

**Comment by hlissner** [comment]
Also, I'm curious, but what does `window-system` contain on your system? That background color looks like #222222 (used in terminal Emacs) rather than "#22252c" (for GUI emacs).

**Comment by SavchenkoValeriy** [comment]
`window-system` is `x`. I was talking about the text colors, on your screenshots they look much more vibrant.
BTW I've tried `doom-buffer-mode`, it makes background brighter and this is not what I was looking for.
Thank you for your reply!

**Comment by hlissner** [comment]
Ah! My bad. In that case, yes, a few of the syntax groups have been _slightly_ dimmed (to match Atom; whose colors are more washed out), a change I somewhat regret. Over the weekend I plan to add another theme to this repo (doom-classic?) that will restore its more vibrant palette.

**Comment by SavchenkoValeriy** [comment]
Oh, neat! That would be very nice of you.
