### ISSUE TITLE
background color issue in iterm

### ISSUE THREAD

**Issue by akkinenivijay** [hlissner/emacs-doom-theme#2]
Hi,

  Thank you for the excellent theme, however i am facing a background color issue when i open emacs in ITerm or Terminal. Emacs is getting loaded with a blue background. Emacs version is 25.1. Not sure if this is an issue with the theme or some emacs customization issue.

![screen shot 2016-07-15 at 5 15 37 pm](https://cloud.githubusercontent.com/assets/334752/16888860/98740d30-4ab0-11e6-83a2-a88948910a3b.png)

**Comment by hlissner** [comment]
Sorry to say, doom-one was designed for GUI Emacs (that's why I created doom-dark; for terminal emacs). I will look into improve doom-one's terminal compatibility, however.

**Comment by hlissner** [comment]
I just pushed a few fixes for doom-one in the terminal. It's not comprehensive, but it should fix the most glaring issues. Let me know if it does.
