### ISSUE TITLE
Modeline colors don't seem to work since faces don't exist

### ISSUE THREAD

**Issue by dakrone** [hlissner/emacs-doom-theme#20]
Currently doom theme defines things like:

```
     ;; Custom (doom)
     `(doom-modeline-buffer-path       ((,c (:foreground ,white :bold ,bold))))
     `(doom-modeline-buffer-project    ((,c (:foreground ,fg))))
     `(doom-modeline-buffer-modified   ((,c (:foreground ,blue))))
     `(doom-modeline-buffer-major-mode ((,c (:foreground ,white :bold ,bold))))

     `(doom-modeline-highlight     ((,c (:foreground ,blue))))
     `(doom-modeline-panel         ((,c (:foreground ,black :background ,blue))))
     `(doom-modeline-bar           ((,c (:background ,blue))))
     `(doom-modeline-eldoc-bar     ((,c (:background ,yellow))))

     ;; Powerline/Spaceline
     `(spaceline-highlight-face    ((,c (:inherit doom-modeline-panel))))
     `(powerline-active1           ((,c (:inherit doom-modeline-panel))))
     `(powerline-active2           ((,c (:inherit doom-modeline-highlight))))
     `(powerline-inactive1         ((,c (:inherit mode-line-inactive))))
     `(powerline-inactive2         ((,c (:inherit mode-line-inactive))))
```

However, since the `doom-modeline-panel` (all `doom-modeline-*` faces) don't exist, the spaceline/powerline faces end up referencing a face that does not exist. This causes the modeline to be entirely uncolored, like:

![screenshot from 2016-10-07 09-42-51](https://cloud.githubusercontent.com/assets/19060/19196357/6fcc42ae-8c72-11e6-8728-ef4e5fc57161.png)

I think the faces need to be created somewhere, as evaling the `custom-theme-set-faces` s-exp doesn't create them. This is also necessary since your custom modeline does not exist in an installable package, so it's not marked as a dependency for this theme.

**Comment by hlissner** [comment]
You're right. Those faces are defined in a mode-line component I haven't published yet. I'll put up a skeleton file with the faces defined for the team being.
