### ISSUE TITLE
Make current active mode-line a little lighter

### ISSUE THREAD

**Issue by stardiviner** [hlissner/emacs-doom-theme#23]
As the title described.
Here is the idea: https://github.com/wasamasa/eyebrowse#quick-tutorial

**Comment by mdbenito** [comment]
I think `doom-lighten` by a moderate amount does the trick, e.g. in doom-one.el change the line for modeline-bg to:
`(modeline-bg (doom-lighten (if window-system bg-d current-line) 0.08))`
But maybe this should be made an option like doom-enable-brighter-comments ?

**Comment by hlissner** [comment]
Yikes, I must've missed this issue in my feed. I'd like to make this another option, possibly `doom-enable-brighter-modeline`, because I like the way it is. I'll look into it this weekend.

**Comment by stardiviner** [comment]
@hlissner thanks

**Comment by hlissner** [comment]
I've added the `doom-one-brighter-modeline` option, which will make the modeline _slightly_ brighter for users that aren't using `doom-buffer-mode`. Let me know if that works for you.

**Comment by stardiviner** [comment]
It works, thanks.
