### ISSUE TITLE
blue cursor collides with show-paren-mode

### ISSUE THREAD

**Issue by cocreature** [hlissner/emacs-doom-theme#25]
1cfecf5ef9e94a94cf33f0b8408c8ef810fd527c enabled a blue cursor by default. Unfortunately this makes the cursor invisible if it is on the left parantheses and `show-paren-mode` is enabled. See the attached image where the cursor is on the left parenthesis.
![leftparen](https://cloud.githubusercontent.com/assets/1313584/20457291/2b8b79a6-ae88-11e6-8296-99269013c5cc.png)

It looks like the face responsible is `show-paren-match`. I don’t have any clever suggestions on how to fix this apart from either changing the cursor back to white or finding a pretty color for `show-paren-match` that doesn’t collide.

`show-smartparens-mode` suffers from the same problem but its faces inherit from `show-paren-match` so this should fix both.

**Comment by rakanalh** [comment]
I also have this problem... when the cursor is at one of the parens, it's confusing as to on which one i am currently pointing.
![SC](http://i.imgur.com/CpuZndW.png)

**Comment by hlissner** [comment]
Oops! I hadn't taken that into account. I'll look into this tomorrow.

**Comment by ppiotrowicz** [comment]
Hey, removing invert-video for show-paren-match works for me.

![doom-parens](https://cloud.githubusercontent.com/assets/138331/20649043/60c0fd6a-b4b6-11e6-9f89-fe8a0c0ba056.png)

**Comment by hlissner** [comment]
I've pushed a solution: show-paren is now a brighter and bold red. This is so it can still stand out in case `rainbow-delimiters` is being used. I might've overlooked something though. Let me know if you have any trouble with it, I'm still considering alternatives.

**Comment by hlissner** [comment]
I've made it a tiny bit more prominent. I think this is as good as I can get it without straying too far from the core colorscheme, so I consider this resolved. Let me know if you find anything amiss.
