### ISSUE TITLE
Can't load theme, no such file or directory, doom

### ISSUE THREAD

**Issue by FilipMiletic** [hlissner/emacs-doom-theme#3]
I am probably doing something wrong, and error is on my part, so sorry for that in advance.
When I copy all files from repo to my theme sourced directory and try load-theme it gives
me the next error message: 

> Cannot open load file: No such file or directory, doom

So does it mean I need few more packages to install that aren't mentioned in description or just dash?

**Comment by rakanalh** [comment]
You have to do something as follows:
```
(add-to-list 'load-path "~/.emacs.d/themes/emacs-doom-theme/")
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/emacs-doom-theme")
```
