### ISSUE TITLE
org-level-1 font has unexpected behavior when moving cursor through characters

### ISSUE THREAD

**Issue by chaseadamsio** [hlissner/emacs-doom-theme#30]
I've been using doom-theme and it's been BY FAR the best theme I've used in vim or emacs (nice work, this is awesome!)

I have experienced one issue: the line width for `org-level-1` makes the font do weird things when you move your cursor through it (I've attached an animated gif):

![doom-experienced](https://cloud.githubusercontent.com/assets/1024544/21492540/868459b4-cbba-11e6-9605-03e2a452ba9a.gif)

I tested by removing this from my local copy (`(:line-width 4 :color ,current-line)`) and I get what I expect: 

![doom-expected](https://cloud.githubusercontent.com/assets/1024544/21492541/868663bc-cbba-11e6-8aa2-58ac4f5d14f1.gif)

I don't really know what's going on here, but I was wondering if you experienced it as well.

I've added the following to my `init.org` to override it temporarily and as a measure to help anyone else who may experience it in the meantime:

```
#+BEGIN_SRC emacs-lisp
(custom-set-faces
  '(org-level-1 ((t (:line-width 1))))
)
#+END_SRC
```

**Comment by hlissner** [comment]
That is quite strange. I'll look into it this weekend.

**Comment by hlissner** [comment]
I've simply removed the padding altogether (I may revisit this if I figure out the problem).

**Comment by chaseadamsio** [comment]
curious, were you able to replicate the issue? PS, THANK YOU so much for this awesome theme. I've been able to drum up interest in Emacs because of how awesome my env looks. :)

**Comment by hlissner** [comment]
No I haven't. I _have_ seen it before, but I couldn't consistently reproduce it way back when (and I've jumped a few OSes and Emacs builds + major versions since. And you're very welcome! I'm happy that I could get Emacs to look this nice!
