### ISSUE TITLE
RPM spec file support

### ISSUE THREAD

**Issue by gicmo** [hlissner/emacs-doom-theme#34]
Currently colors (esp. the blue) for RPM spec files look off and are hard to read (see below). I guess this mode is not use that much, maybe when I have some free time I could look into fixing this myself.

![doom-rpm-spec-mode-colors](https://cloud.githubusercontent.com/assets/2040/21776647/c33beaa2-d69b-11e6-977f-8ac555c3a161.png)

**Comment by hlissner** [comment]
I'm assuming you're using `rpm-spec-mode`. For my reference, I'll post their faces here:

```
rpm-spec-macro-face
rpm-spec-var-face
rpm-spec-tag-face
rpm-spec-obsolete-tag-face
rpm-spec-package-face
rpm-spec-dir-face
rpm-spec-doc-face
rpm-spec-ghost-face
rpm-spec-section-face
```

**Comment by hlissner** [comment]
And done. Let me know if it gives you any trouble!

**Comment by gicmo** [comment]
Thanks a lot, much appreciated!
