### ISSUE TITLE
Inserting new parens and continuing edit has a blue background throughout

### ISSUE THREAD

**Issue by ashutoshrishi** [hlissner/emacs-doom-theme#35]
I don't know if this is through the theme or I am not setting something properly, but when I insert a new parenthesis (have smartparens mode), and start inserting characters, the blue highlight stays put making text hard to read:

![screen shot 2017-01-18 at 10 45 48 pm](https://cloud.githubusercontent.com/assets/176255/22062855/04e285fc-ddd0-11e6-88d4-ccba5ee58141.png)

- It is fine if I move my cursor and then edit, the highlight disappears. 
- Another theme that I use does not have this problem so I am not sure what emacs settings I need to change.

Thanks!

**Comment by ashutoshrishi** [comment]
I have gotten around this atm by:
  ```
(setq sp-highlight-pair-overlay nil)
(setq sp-show-pair-from-inside t)
```

**Comment by hlissner** [comment]
I added a face for sp-pair-overlay-face, which should make the highlight much easier on the eyes. Let me know if it's still a problem.
