### ISSUE TITLE
[swiper] Current match invisible

### ISSUE THREAD

**Issue by cocreature** [hlissner/emacs-doom-theme#4]
First of all let me thank you for this awesome theme!

![swiper](https://cloud.githubusercontent.com/assets/1313584/18320918/226d04d8-752c-11e6-86ff-ca9c70b3c19f.png)

It looks like the two faces colliding here are `swiper-line-face` which inherits from `highlight` and `swiper-match-face-2` inheriting from `isearch`. Personally I think it makes more sense to change `swiper-line-face` to something darker but I don’t have any strong opinion here or a good suggestion on which face would make sense.

**Comment by hlissner** [comment]
Whoops! I agree, that's definitely an oversight. I'll experiment a little and push something up in a couple minutes.

**Comment by hlissner** [comment]
Just pushed a fix for this; I darkened swiper-line-face and customized each of the ivy+swiper faces to fit in better with doom-one as a whole. Let me know if you find another conflict!

**Comment by cocreature** [comment]
Thanks!
