### ISSUE TITLE
Funky colors with dired-x enabled

### ISSUE THREAD

**Issue by gicmo** [hlissner/emacs-doom-theme#43]
I have enabled `dired-x` and what were nice colors before turned into a more funky version ;)
![dired_funny_colors](https://cloud.githubusercontent.com/assets/2040/23898047/d48c3460-08af-11e7-9945-de23fa70fe0c.png)

**Comment by hlissner** [comment]
Those are pretty funky! I'll look into dired-x's faces and see what i can do.

**Comment by hlissner** [comment]
Huh, doesn't seem like it's originating from dired-x (it has no faces), and i haven't been able to reproduce the issue. Could you share your dired config?

**Comment by gicmo** [comment]
Hmm, I think that as the only thing I changed though. Config is here https://github.com/gicmo/dot-emacs/blob/master/init.el#L110

**Comment by hlissner** [comment]
Alright, that should do it. It was dired+ that was doing it. Might need some more tweaking, but the colors aren't so outlandish anymore.

**Comment by gicmo** [comment]
Way better, thanks a lot!
