### ISSUE TITLE
Multiple cursors don't show up

### ISSUE THREAD

**Issue by iAmMrinal0** [hlissner/emacs-doom-theme#45]
Multiple cursors selection works and multiple regions are highlighted whereas adding new cursors don't show up. The cursors are there just not highlighted.

**Comment by hlissner** [comment]
I assume you're using multiple-cursors. Could you add this to your emacs.d and let me know if they become visible:

```elisp
(custom-set-faces
 '(mc/cursor-face ((((class color)) (:background "red")))))
```

**Comment by iAmMrinal0** [comment]
No, not visible. And I just noticed that this(cursors not being visible) happens only when I start emacs as daemon and open files using emacsclient. If I don't start it and open `emacs filename` the multiple cursors are visible and shows up as `black`

**Comment by iAmMrinal0** [comment]
My mistake, sorry. It works properly.
I am not sure why this happens but I figured that `js2-refactor` caused this issue. I use `use-package` and when I `defer` `js2-refactor` the cursors show up but when I don't they don't show up. I currently don't have the knowledge to make sure that `js2-refactor` is causing this.
