### ISSUE TITLE
Neotree setup

### ISSUE THREAD

**Issue by jwintz** [hlissner/emacs-doom-theme#48]
@hlissner,

After one day of work, I will definitely keep this theme, and hopefully, contribute a bit.

I have a question though:

With:

```emacs-lisp
(require 'doom-neotree)  
```

<img width="1124" alt="screen shot 2017-04-18 at 18 39 13" src="https://cloud.githubusercontent.com/assets/3277054/25142317/c5a021e6-2466-11e7-98e6-324c515fadc3.png">

The neotree is most beautiful: no fringe or fringe coloured as expected, however, `major-modes` for files are not showing as opposed to:

```emacs-lisp
;; (require 'doom-neotree)  
```

Where `major-mode` icons are rendered as expected, but the fringe (or whatever margin) is messed up.

<img width="1084" alt="screen shot 2017-04-18 at 18 44 24" src="https://cloud.githubusercontent.com/assets/3277054/25142415/169a1d22-2467-11e7-88b0-fdf74ec93959.png">

Is there any way to combine these two excellent features ?

Many thanks !

  - ju

**Comment by hlissner** [comment]
Hi there! The default is `(setq doom-neotree-file-icons 'simple)`, which is my personal preference, but you can get the major-mode icons by setting: `(setq doom-neotree-file-icons t)`. Let me know if that solves your issue!

**Comment by jwintz** [comment]
Should have tried `M-x customize-group` before, if it is available.

That works indeed ! Thanks for this awesome theme ;-)

**Comment by jupl** [comment]
@jwintz Totally off topic, but how is it that you have a dark title bar like in the screenshots?

**Comment by hlissner** [comment]
I presume he's using [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus).

```sh
brew tap d12frosted/emacs-plus
brew install emacs-plus --with-natural-title-bar
```

```
--with-natural-title-bar
	Experimental: use a title bar colour inferred by your theme
```
