### ISSUE TITLE
vc-modified is now grey ... intentional?

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/emacs-doom-theme#51]
Is changing ```vc-modified``` face to grey an intentional change? The grey color is incredibly hard to pick out in the fringe, whereas the previous yellow color stood out much better. Thanks!

**Comment by hlissner** [comment]
My bad! This was not intentional. I'm doing a big refactor of this package to prepare for the addition of more color themes and this must've slipped in during experimentation. I'll revert it soon!

**Comment by hlissner** [comment]
And done!

**Comment by gilbertw1** [comment]
awesome! 👍
