### ISSUE TITLE
Make modeline styling optional

### ISSUE THREAD

**Issue by etyurkin** [hlissner/emacs-doom-theme#62]
Thanks for the great theme, I'm using it daily and never looked back.

The minor inconvenience is I have my own style for modeline\spaceline and every time I update doom theme it gets overridden.
Please add a configuration option to exclude modeline styling.

**Comment by hlissner** [comment]
I'm guessing you are a `doom-buffer-mode` user, and you're bothered that it changes the mode-line when you activate/deactivate that mode?

**Comment by etyurkin** [comment]
Nope, here's my modeline config:

`  (set-face-attribute 'mode-line nil :foreground "gray" :background nil :box nil)
  (set-face-attribute 'mode-line-inactive nil :foreground "SkyBlue4" :background nil :box nil)
  (set-face-attribute 'powerline-active1 nil :foreground "SkyBlue1" :background "SkyBlue4")
  (set-face-attribute 'powerline-active2 nil :foreground "white" :background nil)
  (set-face-attribute 'powerline-inactive1 nil :foreground "SkyBlue4" :background nil)
  (set-face-attribute 'powerline-inactive2 nil :foreground "SkyBlue4" :background nil)
  (set-face-attribute 'spaceline-highlight-face nil :foreground "SkyBlue1" :background "SkyBlue4")

  (setq powerline-default-separator 'curve)
  (spaceline-emacs-theme)
`

It gives me nice curved separators, but if I activate doom-one theme it overrides these values and it doesn't look as I want anymore. I can set these values after theme activation and it works fine when emacs is starting but breaks every time doom package is updated.

**Comment by hlissner** [comment]
Use `custom-set-faces` instead, as it doesn't get overwritten when the theme is reloaded:

```emacs-lisp
(custom-set-faces
   `(mode-line                ((t (:inherit nil :foreground "red"      :background nil))))
   `(mode-line-inactive       ((t (:inherit nil :foreground "red"      :background nil :box nil))))
   `(powerline-active1        ((t (:inherit nil :foreground "red"      :background "SkyBlue4"))))
   `(powerline-active2        ((t (:inherit nil :foreground "white"    :background nil))))
   `(powerline-inactive1      ((t (:inherit nil :foreground "SkyBlue4" :background nil))))
   `(powerline-inactive2      ((t (:inherit nil :foreground "SkyBlue4" :background nil))))
   `(spaceline-highlight-face ((t (:inherit nil :foreground "SkyBlue1" :background "SkyBlue4")))))
```

**Comment by hlissner** [comment]
Another alternative:

```emacs-lisp
  (defun apply-theme (&rest _)
    ;; put your apply-theme config here
    )
  (advice-add #'load-theme :after #'apply-theme)
```

Then whenever you reload your theme, `apply-theme` will automatically run.

**Comment by etyurkin** [comment]
That works, thanks!
