### ISSUE TITLE
Fringe before line numbers

### ISSUE THREAD

**Issue by tudurom** [hlissner/emacs-doom-theme#67]
Hello!

First of all, this is more of a question than an issue, sorry for that.

I like the thin line git gutter indicators so I tried implementing them in my emacs config. I noticed that on my emacs the fringe is drawn after the line numbers, whereas in your screenshot the thin lines are drawn on the left of the line numbers.

I find this behavior quite uncomfortable, so my question is, how do I make the lines appear on the left of the line number?

Here is a quick comparison:

![Comparison](https://ptpb.pw/IRa0.png)

**Comment by hlissner** [comment]
The secret to this is `fringes-outside-margins`

```emacs-lisp
(setq-default fringes-outside-margins t)
```

**Comment by rakanalh** [comment]
I was able to extract this out from @hlissner's configs only yesterday along with the modeline.
Here's the block that can handle this for you:
```
https://github.com/rakanalh/dotemacs/blob/master/core/core-ui.el#L39
```

**Comment by tudurom** [comment]
For some reason I didn't see that line when looking at the code when I last checked. Thank you very much!
