### ISSUE TITLE
 Symbol’s value as variable is void: doom-neotree-folder-size

### ISSUE THREAD

**Issue by rakanalh** [hlissner/emacs-doom-theme#7]
This is caused when installing `doom-themes` from Melpa with `all-the-icons`.

I had to set it manually
```
(use-package doom-themes
  :config
  (load-theme 'doom-one t)
  (require 'doom-neotree)
  (setq  doom-neotree-folder-size 120))
```

**Comment by hlissner** [comment]
Aah, I derped hard and accidentally removed a variable declaration. I've fixed it in the latest push.

**Comment by rakanalh** [comment]
Thanks!

**Comment by hlissner** [comment]
By the way, if you (or anyone) still has this problem, it can be fixed by adding `(defvar doom-neotree-folder-size 1.1)` to your emacs.d for the time being.

**Comment by rakanalh** [comment]
Yup, i set it `(setq  doom-neotree-folder-size 120)` but i didn't know it was a float value... I also think that 1.1 is a little too small, maybe 1.3 - 1.5 might work better.

**Comment by hlissner** [comment]
Either float or integer will work actually (hadn't occurred to me!). Feel free to customize it though (that's what it's there for). I'm on a small 13' laptop so it seemed like a good default.

Would you mind showing me a screenshot of your settings? I've been worried about how it would look on other people's setups.

**Comment by rakanalh** [comment]
Sure... on 1.5 it looks like this:
![Screenshot](http://imgur.com/a/mrQ1j)

**Comment by hlissner** [comment]
Fantastic, good to know it came out well. Thanks!

**Comment by rakanalh** [comment]
Yup... however, my previous manual installation which i copied off your emacs.d had the folder icon color as blue. Could you please add an option to customize that? i can create a separate issue for this if needed.

**Comment by hlissner** [comment]
> Could you please add an option to customize that? 
Certainly. 

>i can create a separate issue for this if needed.
Please do. It makes its easier for others to search for these things.
