### ISSUE TITLE
Neotree integration : no icon for files

### ISSUE THREAD

**Issue by nlamirault** [hlissner/emacs-doom-theme#8]
Hi, 
using the neotree integration, i've got icons like in the screenshots for folders, but no icons for files.
Any idea ?

**Comment by hlissner** [comment]
They are disabled by default and can be enabled with `(setq doom-neotree-enable-file-icons t)`

**Comment by nlamirault** [comment]
Thanks ! It works. But some icons are very BIG :(
any idea ?

http://www.hostingpics.net/viewer.php?id=91749320160915121256268x798scrot.png

**Comment by hlissner** [comment]
Whoa! That _is_ bizarre. I can't reproduce the problem. Could your show me your neotree + doom configuration? Or, if you have your emacs.d on github, a link to the repo?

**Comment by kwrooijen** [comment]
I seem to be having the same issue.
https://s17.postimg.io/7yquh6767/Screenshot_from_2016_09_15_14_24_10.png

Running Linux, Emacs 25.1.1, and Spacemacs.

(afaik) these are all the spacemacs neotree configs  https://github.com/syl20bnr/spacemacs/blob/9f9faa404e3dec3e08cc73cf7b5a0439fc309800/layers/%2Bdistribution/spacemacs/packages.el#L1478-L1489

However I've tried playing around with these values, only to end up with the same result. Maybe it's an Emacs version issue?

**Comment by hlissner** [comment]
If it isn't too much trouble, could either or both of you try this in a `fundamental-mode` buffer (you can use `M-x eval-expression`):

```elisp
(insert (all-the-icons-icon-for-file "test.py"))
```

```elisp
(insert 
  (propertize (all-the-icons-icon-for-file "test.py")
              'face `(:height 1 :family ,(all-the-icons-icon-family-for-file "test.py"))))
```

(Change the file name to match the type of file you get large icons for, e.g. @nlamirault seems to have it for python and html files)

Please take a screenshot of the result.

**Comment by kwrooijen** [comment]
Here you go
https://s9.postimg.io/jzuzm0dbz/Screenshot_from_2016_09_15_15_03_15.png

Going to try to downgrade to Emacs 24 and see if that makes a difference

**Comment by hlissner** [comment]
It shouldn't, I am using Emacs 25.1.1 too and do not see the issue. I'm on a mac, however.

If you're sure that you have installed its fonts, this looks like it may be an `all-the-icons` bug. I'll see what I can find out.

**Comment by nlamirault** [comment]
Same behavior, a big icon, in Emacs 24.5 and 25. with : 

```
(insert (all-the-icons-icon-for-file "test.py"))
(insert 
  (propertize (all-the-icons-icon-for-file "test.py")
              'face `(:height 1 :family ,(all-the-icons-icon-family-for-file "test.py"))))
```

**Comment by kwrooijen** [comment]
I guess it's safe to say it's a bug on all-the-icons side, I'll open a ticket and refer this one.

**Comment by kwrooijen** [comment]
Seems to be an issue with a specific icon set.
https://github.com/domtronn/all-the-icons.el/issues/6

So I'd say that this issue can be closed. Thanks for the help!

**Comment by hlissner** [comment]
Good to know! And no problem!
