### ISSUE TITLE
Unify fringes background color with bg

### ISSUE THREAD

**Issue by rakanalh** [hlissner/emacs-doom-theme#9]
Hi,

I find it quite annoying to have the left-fringe and right-fringe background colors different than the main `bg` defined in the theme.

Screenshots:
![image1](http://image.prntscr.com/image/64282b9219a345338ed164df087de33a.png)
![image2](http://image.prntscr.com/image/c8251fda059c433ab8eb5e67ea00d29d.png)
![image3](http://image.prntscr.com/image/6813f0dd3ef24cf9acec2310e49cfbcb.png)

The first 2 images show left fringe background color and right-fringe background color. The third one however shows how line highlight color is the same as both fringe background colors. I think we can just keep the same color for current line if we just unify both fringes with the main `bg`.

Wish i could be as good as you are with elisp, i would have posted a PR, but am getting there so maybe i can get to help in the near future.

Thanks alot!

**Comment by hlissner** [comment]
Oh! You're right. I wrote the theme expecting people to use the `doom-buffer-mode` feature (where [source buffers are highlighted](https://raw.githubusercontent.com/hlissner/emacs-doom-theme/screenshots/doom-one.png)) -- so I forgot about the use case without it. I'll look into it.

**Comment by rakanalh** [comment]
Thank you!
